config/routes.rb
Brog::Application.routes.draw do
  root 'welcome#index'

  mount Social::Engine => '/social', as: :social_ng
    
  resources :blog_posts do
    resources :comments, only: [:show, :index, :create], controller: 'social/comments'
  end
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  include Social::Concerns::Commentable
  
  # Validations...
  validates_presence_of :title, :content
  
  # Scopes...
  scope :sort_recent, -> { order( created_at: :desc ) }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # Relationships...
  belongs_to :commentable, polymorphic: true
  
  # Validations...
  validates_presence_of :content, :commentable
  
  # Scope...
  scope :sort_recent, -> { sort( created_at: :desc ) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  helper Social::CommentsHelper
  
  def index
    @blog_posts = BlogPost.includes(:comments).sort_recent
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Blog post was successfully deleted!" }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
  def flash_class(level)
    @clazz ||= {notice: :success, alert: :error }
    @class[level.to_sym] || level
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  def majusculize( text )
    truncate( text.upcase, length: 30 )
  end
end

app/helpers/comments_helper.rb
module CommentsHelper  
  def minusculize( text )
    text.downcase.capitalize
  end
end

app/views/blog_posts/_form.html.haml
=form_for(@blog_post) do |f|
  -if @blog_post.errors.any?
    .alert.alert-error{ id: 'error_explanation' }
      %button.close{ 'type'=>'button', 'data-dismiss'=>'alert' }
        &times;
      %span The following errors prevented this post from being saved:
      %ul
        -@blog_post.errors.full_messages.each do |msg|
          %li= msg

  .field
    =f.label :title
    =f.text_field :title, placeholder: 'Your title', autofocus: true

  .field
    =f.label :content
    =f.text_area :content, placeholder: 'Your article'

  .actions
    =f.submit (@blog_post.new_record? ? "Create" : "Update"), class: "btn"
    =link_to 'Cancel', blog_posts_path

app/views/blog_posts/edit.html.haml
%h1 Editing a post
=render 'form'

app/views/blog_posts/index.html.haml
.row-fluid
  .row.heading.span11
    %h1.span10 Bro's happenings...
    =link_to 'New post', new_blog_post_path, class: "btn btn-default pull-right"
      
  .row.span11
    %ul.posts
      -@blog_posts.each do |blog_post|
        %li
          .row
            %h2.span9
              %span.icon-quote-left
              =majusculize blog_post.title
      
            .controls.span2
              =link_to content_tag( :i, "", class: 'icon-pencil'), edit_blog_post_path(blog_post), 
                class:  "btn", id: "ed_#{dom_id(blog_post)}"
              =link_to content_tag( :i, "", class: 'icon-trash'), blog_post, 
                method: :delete, 
                data:   {confirm: 'Are you sure?'}, 
                class:  "btn", id: "del_#{dom_id(blog_post)}"
             
          .row 
            .timestamp= time_ago_in_words( blog_post.created_at )
        
          .row
            .content.rounded= blog_post.content
                  
          %div.comments{ 'id' => "comments_#{dom_id(blog_post)}" }
            .summary{ 'id' => "summary_#{dom_id(blog_post)}", 'data-id'=>blog_post.id }
              %span.icon-comments
              %span.comment-count{ 'data-id'=>blog_post.id }= blog_post.comments.size
              %span= 'comment'.pluralize( blog_post.comments.size)
            %ul.comments{ 'data-id'=>blog_post.id, style:'display:none' }
              =render partial: 'social/comments/comment', 
                collection: blog_post.comments.sort { |a,b| b.created_at <=> a.created_at }
              =render partial: 'social/comments/form', locals: { blog_post: blog_post }

app/views/blog_posts/new.html.haml
%h1 New Post
=render 'form'

app/views/layouts/application.html.haml
!!! 5
%html{ lang: 'en' }
  %head
    %title Teh Brog
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false
    = javascript_include_tag "application", "data-turbolinks-track" => false
    = csrf_meta_tags

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %button.bth.btn-navbar{ type: :button, "data-toggle" => :collapse, "data-target" => ".nav-collapse" }
            %icon-bar
            %icon-bar
            %icon-bar
          =link_to "Teh Brog", root_path, class: "brand"
          %div.nav-collapse.collapse.pull-right
            %ul.nav
              %li
                =link_to content_tag( :i, "", class: 'icon-home') + " Home", root_path
              %li
                =link_to content_tag( :i, "", class: 'icon-quote-left') + " Articles", blog_posts_path

    #wrap   
      %div.container
        .alert{ style: 'display:none' }
          %div#alert-message
      
        = yield
        #push

app/views/welcome/index.html.haml
.content-pane
  = image_tag 'mullet.png'
  %h1 You rock Bro!